id: I258BACCA
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-04-01T01:44:16+00:00'
last_modified: '2022-06-08T17:34:32.428027+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1AC278
  title: རྗེ་བཙུན་ཤེས་རབ་རྒྱ་མཚོ་འཇམ་དཔལ་དགྱེས་པའི་བློ་གྲོས་ཀྱི་གསུང་རྩོམ།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: true
  base:
    '8866':
      image_group_id: I2PD20351
      title: ''
      total_pages: 572
      order: 1
      base_file: 8866.txt
    9E33:
      image_group_id: I2PD20352
      title: ''
      total_pages: 688
      order: 2
      base_file: 9E33.txt
    '9934':
      image_group_id: I2PD20353
      title: ''
      total_pages: 686
      order: 3
      base_file: 9934.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
